# -*- coding: utf-8 -*-
"""coba_streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDKBNxyTX_MGBgIOWfYk1uxo-8-7xpDQ
"""

!pip install streamlit

import streamlit as st

st.write(
    """
    # My first app
    Hello, para calon praktisi data masa depan!
    """
)